baseURL = 'https://mazama923.github.io/vermeauplomberie/'
languageCode = 'fr'
title = "Verm'eau plomberie"
theme = 'ananke'

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Verm'eau plomberie"
favicon = "favicon.svg"
site_logo = "logo.svg"
description = "Service de plomberie professionnel à Clermont-Ferrand, Issoire, Vic-le-Comte et les environs"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
